services:
  - type: web
    name: bolao-panceta-copa-2026
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Math
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
